### ISSUE TITLE
Prettier exits with error code 2 when no files match glob pattern

### ISSUE THREAD

**Issue by atagulalan** [Commencis/starter-react-vite#88]
When running `pnpm run lint` on **macOS Sequoia 15.2**, Prettier exits with **error code 2** if no files match the specified glob pattern. This causes the entire lint script to fail.

**Error Example:**
```
[error] No files matching the pattern were found: "**/*.md".
```
**Cause:**
Prettier throws an error when it doesn't find any files matching the provided glob pattern. This behavior interrupts the script execution.

**Solution:**
Wrap the glob pattern in quotes to prevent the shell from interpreting it incorrectly and avoid Prettier failing due to no matches.

For example:
```bash
prettier "**/*.js"  --check
```

Further Details: Refer to this [StackOverflow discussion](https://stackoverflow.com/questions/63070243/getting-an-error-no-files-matching-the-pattern-were-found-when-using-prettier) for additional context and solutions.

Steps to Reproduce:
- Run pnpm run lint with Prettier.
- Ensure the glob pattern does not match any files.
- Expected Behavior: Prettier should handle an empty match gracefully and not fail the entire script.

Environment:
OS: macOS Sequoia 15.2
Package Manager: pnpm
Script: `pnpm run lint` (or any other lint sequence uses prettier)

**Comment by ymehmetcan** [comment]
Thanks for the feedback! The issue occurred because the `README.md` file, which is the only Markdown file in the generation part of Commencis-CLI, was removed. This is an active issue that will be addressed in the next version to provide a project-specific `README` during generation. Additionally, it would be best to update the Prettier script to include the glob pattern you proposed.
